# Generated by Django 3.1.3 on 2021-03-24 06:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Prescriptions', '0001_initial'),
        ('PurchaseRequests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('purchaserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PurchaseRequests.purchaserequest')),
            ],
            options={
                'verbose_name': 'Order Request',
            },
            bases=('PurchaseRequests.purchaserequest',),
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('item_type', models.CharField(blank=True, max_length=20, null=True)),
                ('cost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='requester',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='request_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='PrescriptionRequest',
            fields=[
                ('purchaserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PurchaseRequests.purchaserequest')),
                ('prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Request',
            },
            bases=('PurchaseRequests.purchaserequest',),
        ),
        migrations.CreateModel(
            name='PaymentSlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('prescription_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseRequests.prescriptionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('requestitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PurchaseRequests.requestitem')),
                ('medicine_recordMedicineRecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prescriptions.medicinerecord')),
                ('prescription_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseRequests.prescriptionrequest')),
            ],
            options={
                'verbose_name': 'Presription Item',
            },
            bases=('PurchaseRequests.requestitem',),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('requestitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PurchaseRequests.requestitem')),
                ('order_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseRequests.orderrequest')),
            ],
            bases=('PurchaseRequests.requestitem',),
        ),
    ]
