# Generated by Django 3.1.3 on 2021-04-20 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_customer_is_rejected'),
        ('Products', '0002_auto_20210409_1301'),
        ('PurchaseRequests', '0002_auto_20210324_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitem',
            name='item_type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='item_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PurchaseRequests.orderrequest'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
