# Generated by Django 3.1.3 on 2021-03-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20210323_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Pharmacy Owner'},
        ),
        migrations.AlterModelOptions(
            name='pharmacyworker',
            options={'verbose_name': 'Pharmacy Worker'},
        ),
    ]
