# Generated by Django 3.1.3 on 2021-03-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20210323_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='valid_id1',
            field=models.FileField(blank=True, null=True, upload_to='customer_ids'),
        ),
        migrations.AddField(
            model_name='owner',
            name='business_permit',
            field=models.FileField(blank=True, null=True, upload_to='business_permit'),
        ),
        migrations.AddField(
            model_name='pharmacyworker',
            name='medical_license',
            field=models.FileField(blank=True, null=True, upload_to='medical_licences'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='medical_record',
            field=models.FileField(blank=True, null=True, upload_to='customer_medical_records'),
        ),
    ]
