# Generated by Django 3.1.3 on 2021-03-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20210324_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
